Repository blocknative/assist, pull requests merged in 2019-06, with the labels that each got.

#251 Readme edits
  README.md
Labels: documentation

#234 coerce network id type to Number in getNetworkID and remove coercion …
  src/js/helpers/utilities.js
  src/js/helpers/web3.js
  src/js/logic/user.js
  src/js/views/content.js
Labels: enhancement

#253 Improve Transaction custom inline message docs
  README.md
Labels: documentation

#260 Fix type with contract method call
  README.md
Labels: documentation

#263 Add resolving init onboard promise
  src/js/helpers/state.js
  src/js/index.js
Labels: bug

#266 remove MM specific language on mobile
  src/js/views/content.js
Labels: bug

#269 add dapper to getCurrentProvider
  src/js/helpers/web3.js
Labels: enhancement

#274 Check for undefined or null instead of just falsey value in result
  src/js/logic/contract-methods.js
Labels: bug

#283 Access web3 object on window if available
  src/js/index.js
Labels: bug

#281 Propagate errors to promievent
  src/js/helpers/utilities.js
  src/js/logic/send-transaction.js
Labels: bug

#284 Add check to make sure contract parameter is on txObj
  src/js/helpers/transaction-queue.js
Labels: bug

#287 Add listener for escape key to close modal
  src/js/views/dom.js
Labels: enhancement

#294 Fix/missing return
  src/js/logic/contract-methods.js
Labels: bug

#290 Add missing messages parameter
  src/js/index.js
Labels: bug

#288 Add custom timeout for txStall event
  README.md
  src/js/helpers/validation.js
  src/js/logic/send-transaction.js
Labels: enhancement

#299 Make sure keypress listener is removed when modal is closed via click
  src/js/views/dom.js
Labels: bug

#300 Enhancement/remove metamask language images
  src/__integration-tests__/ui-rendering/__snapshots__/index.test.js.snap
  src/css/styles.css
  src/js/views/content.js
  src/js/views/dom.js
Labels: enhancement

#305 Enhancement/tx stall style
  src/__integration-tests__/ui-rendering/__snapshots__/index.test.js.snap
  src/js/helpers/utilities.js
Labels: enhancement

#307 Release/0.9
  .eslintrc.js
  README.md
  internals/jestSetup.js
  multidep.json
  src/__integration-tests__/websockets/index.test.js
  src/__tests__/js/contract/index.test.js
  src/__tests__/js/init.test.js
  src/__tests__/js/web3.test.js
  src/js/helpers/ethers-provider.js
  src/js/helpers/events.js
  src/js/helpers/utilities.js
  src/js/helpers/validation.js
  src/js/helpers/web3.js
  src/js/helpers/websockets.js
  src/js/index.js
  src/js/logic/contract-methods.js
  src/js/logic/send-transaction.js
  src/js/logic/user.js
  src/js/views/content.js
  src/js/views/dom.js
  src/js/views/event-to-ui.js
  yarn.lock
Labels: enhancement

#310 Fix iframe error
  README.md
  src/js/helpers/events.js
Labels: bug

#312 Fix config validation for minimumBalance
  src/js/helpers/validation.js
Labels: bug
