Repository blocknative/assist, pull requests merged in 2019-03, with the labels that each got.

#30 added contractQueryFail eventCode to eventCodeToStep function to fix …
  README.md
  package.json
  src/js/helpers/utilities.js
  src/js/index.js
Labels: review

#34 Changed `Contract` method to use delegation
  .eslintrc.js
  README.md
  package.json
  src/js/index.js
  src/js/logic/contract-methods.js
Labels: bug, review

#37 removed build files from repo and updated gitignore
  .gitignore
  lib/assist.js
  lib/assist.min.js
Labels: review

#39 move image source to assist.blocknative.com
  src/css/styles.css
  src/js/views/content.js
Labels: review

#40 format txObject value to make sure that it is not in exponent notation
  src/js/helpers/web3.js
Labels: review

#41 Added the versions of web3 1.0 that have problems with MetaMask
  README.md
Labels: review

#44 disable automated npm build
  .circleci/config.yml
Labels: review

#45 removed UI for contract query fail event
  README.md
  package.json
  src/js/index.js
  src/js/logic/contract-methods.js
  src/js/views/event-to-ui.js
Labels: bug, review

#50 Ensure no iframe is created in headless mode
  src/__tests__/js/init.test.js
  src/js/index.js
Labels: review

#48 log initial state via getState call in init()
  src/js/index.js
Labels: review

#55 Fixes/issues 52 53 54
  src/js/helpers/utilities.js
  src/js/index.js
  src/js/logic/contract-methods.js
  src/js/logic/send-transaction.js
Labels: review

#61 added check to see if existing modal is displayed
  src/js/views/event-to-ui.js
Labels: review

#59 Added large onboard images to js bundle to remove loading time
  .babelrc
  assetsTransformer.js
  babel.config.js
  build.js
  jest.config.js
  package.json
  src/images/0VBtqGV.jpg
  src/images/1TWEHRY.jpg
  src/images/4zplgXa.jpg
  src/images/6mvOkII.png
  src/images/8ptZott.jpg
  src/images/BEhzPx6.jpg
  src/images/EcUxQVJ.jpg
  src/images/EgcXT0z.jpg
  src/images/GS6owd9.jpg
  src/images/HuDHbXP.jpg
  src/images/UhcCuKF.png
  src/images/WjOSJTh.png
  src/images/XAwAAmL.png
  src/images/XLBqwPO.jpg
  src/images/XUPOg7L.jpg
  src/images/elR9xQ8.jpg
  src/images/fJxOtIj.png
  src/images/jJu8b0B.png
  src/images/jfdXqIU.jpg
  src/images/joHkLGC.gif
  src/images/kodZvyO.png
  src/images/maxXVIH.png
  src/images/mqCAjXV.gif
  src/images/riXzN0X.jpg
  src/images/s8euD9T.jpg
  src/images/t7WS9Sc.jpg
  src/images/tKkRH5L.jpg
  src/images/xpWtOVX.jpg
  src/js/views/content.js
  src/js/views/dom.js
  yarn.lock
Labels: review

#65 Fix/general
  package.json
  src/js/helpers/websockets.js
  src/js/index.js
  src/js/views/content.js
  src/js/views/event-to-ui.js
Labels: bug
