Repository blocknative/assist, pull requests merged in 2019-05, with the labels that each got.

#151 scroll container now scrolls to bottom when new notification is added
  src/js/views/dom.js
Labels: bug

#152 Enhancement/onboard returns state
  src/__tests__/js/init.test.js
  src/js/helpers/state.js
  src/js/index.js
Labels: enhancement

#161 updated readme to reflect how onboard resolves with the state object
  README.md
Labels: documentation

#160 Fix/onboard reject state
  src/__tests__/js/init.test.js
  src/js/index.js
Labels: enhancement

#163 Enhancement/network check contract call
  .eslintrc.js
  src/js/logic/contract-methods.js
  src/js/logic/user.js
Labels: enhancement

#169 made sure if user not ready to transact, send transaction returns early
  src/js/logic/send-transaction.js
Labels: bug

#178 Fix/tx stall
  src/js/logic/send-transaction.js
Labels: bug

#175 Race condition
  src/js/helpers/websockets.js
Labels: bug

#180 Fix/promievent
  src/js/logic/send-transaction.js
Labels: bug

#182 cloned inner object from contract method call
  src/js/logic/contract-methods.js
Labels: bug

#184 Fix Duplicate Transaction Check
  src/js/helpers/transaction-queue.js
Labels: bug

#186 add on confirmation method
  src/js/logic/send-transaction.js
Labels: bug

#187 return promievent frim sendTransaction
  README.md
  src/js/logic/send-transaction.js
Labels: bug

#190 Enhancement/onboard mobile
  src/js/helpers/web3.js
  src/js/index.js
Labels: enhancement

#193 Enhancement/mobile ui
  lib/images/coinbase.png
  lib/images/coinbase@2x.png
  lib/images/mobile-wallet-required-white.png
  lib/images/mobile-wallet-required-white@2x.png
  lib/images/mobile-wallet-required.png
  lib/images/mobile-wallet-required@2x.png
  lib/images/trust-original.png
  lib/images/trust-wallet.png
  lib/images/trust.png
  lib/images/trust@2x.png
  package.json
  src/__integration-tests__/ui-rendering/__snapshots__/index.test.js.snap
  src/__tests__/js/contract/index.test.js
  src/css/media-queries.css
  src/css/styles.css
  src/js/helpers/iframe.js
  src/js/helpers/utilities.js
  src/js/helpers/web3.js
  src/js/helpers/websockets.js
  src/js/index.js
  src/js/logic/user.js
  src/js/views/content.js
  src/js/views/dom.js
  src/js/views/event-to-ui.js
Labels: enhancement

#198 resize iframe after hiding modal
  src/js/views/dom.js
Labels: bug

#200 update readme with mobile support info and web3 initialization example
  README.md
Labels: documentation

#204 change pageY and pageX to screenY and screenX
  src/js/views/dom.js
Labels: bug

#206 add correct click handlers to close button touch start event
  src/js/views/dom.js
Labels: bug

#224 remove MetaMask specific language
  src/js/views/content.js
Labels: bug

#226 added condition to fire mobile wallet dialog
  src/js/logic/user.js
Labels: bug

#228 Add touch handlers to not supported modals if on mobile
  src/js/views/event-to-ui.js
Labels: bug

#237 Inline Custom Messages - Transaction
  src/js/index.js
Labels: bug
